version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain demo-domain --domain-owner 156498802103 --query authorizationToken --output text`
      - cp maven-settings.xml ~/.m2/settings.xml
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/aws_codebuild_demo-1.0.jar
